apiVersion: apps/v1
kind: Deployment
metadata:
  name: tyjrd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tyjrd
  template:
    metadata:
      labels:
        app: tyjrd
    spec:
      containers:
      - image: okteto.dev/tyjrd:latest
        name: tyjrd
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "e35b96cb-cd48-4e78-ac1e-dcce7bf7b6c6"
        - name: Vless_Path
          value: "/rthrjj76u65h"
        - name: Vmess_UUID
          value: "e35b96cb-cd48-4e78-ac1e-dcce7bf7b6c6"
        - name: Vmess_Path
          value: "/78i7te6yergwf"
        - name: Share_Path
          value: "/v2link"
